// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-01-02 15:55:52.584161325 +0700 WIB m=+0.093142109

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "-\u003e @h4sb1",
            "email": "justhasby@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add/{key}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "Add -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev ",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add ItemsUepKubePendamping",
                        "name": "sample",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Dummy"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth-Controller"
                ],
                "summary": "SignIn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/download/files/{key}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DownloadFiles-Controller"
                ],
                "summary": "UploadsFiles -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key (string) -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id (int)",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/address": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetAllAddress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "region",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/address_detail": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetAllAddressDetail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/bantuan_periods": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllBantuanPeriods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/chart_dashboard": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetChartDasboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/faq": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetAllFaq",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/jenis_usaha": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllJenisUsaha",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/member_pelatihan": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllMemberPelatihan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "int",
                        "name": "id_pendamping",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/monev_items": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllMonevItems",
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "flag",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/pendamping": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllPendamping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/persebaran": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllUepKubeDetail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/uepkube": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "Get Uep (byNik) or Get Kube (byName)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "val",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/uepkube/pelatihan": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetPaginatePelatihanUepKube",
                "parameters": [
                    {
                        "description": "Show Pelatihan UepKube",
                        "name": "produk",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.PosPagin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/uepkube/produk": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetPaginateProduk",
                "parameters": [
                    {
                        "description": "Show Produk UepKube",
                        "name": "produk",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.PosPagin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/users": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllUser",
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "nik",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/upload/files/{key}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "UploadFiles-Controller"
                ],
                "summary": "UploadsFiles -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key (string) -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id (int)",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Uploads Files",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Uploads Files",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "enums : 'IMAGE', 'PDF' ",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "int (int) -\u003e 0 | 1",
                        "name": "is_display",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/{key}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "GetDetails -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "int",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "for (int) -\u003e uep : 0 | kube : 1",
                        "name": "for",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "Update -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev ",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update ItemsUepKubePendamping",
                        "name": "sample",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Dummy"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "Paginate -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev | pkt",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev | pkt",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Paginate ItemsUepKubePendamping| verifikator",
                        "name": "sample",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.PosPagin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/{key}/{id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "Delete -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev ",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Id -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | log_aktivitas | inventaris | lap_keu | kehadiran | monev ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Activity": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "nama_kegiatan": {
                    "type": "string"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_activity_files"
                    }
                },
                "rincian": {
                    "type": "string"
                },
                "tanggal": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "models.Data_monev": {
            "type": "object",
            "properties": {
                "aspek": {
                    "type": "string"
                },
                "bobot": {
                    "type": "integer"
                },
                "dimensi": {
                    "type": "string"
                },
                "skor": {
                    "type": "integer"
                },
                "skor_total": {
                    "type": "integer"
                }
            }
        },
        "models.Dummy": {
            "type": "object",
            "properties": {
                "activity": {
                    "type": "object",
                    "$ref": "#/definitions/models.Activity"
                },
                "inventory": {
                    "type": "object",
                    "$ref": "#/definitions/models.Inventory"
                },
                "kehadiran": {
                    "type": "object",
                    "$ref": "#/definitions/models.Kehadiran"
                },
                "kube": {
                    "type": "object",
                    "$ref": "#/definitions/models.Kube"
                },
                "lapkeu": {
                    "type": "object",
                    "$ref": "#/definitions/models.Lapkeu"
                },
                "monev": {
                    "type": "object",
                    "$ref": "#/definitions/models.Monev"
                },
                "pelatihan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Pelatihan"
                },
                "pendamping": {
                    "type": "object",
                    "$ref": "#/definitions/models.Pendamping"
                },
                "produk": {
                    "type": "object",
                    "$ref": "#/definitions/models.Produk"
                },
                "uep": {
                    "type": "object",
                    "$ref": "#/definitions/models.Uep"
                },
                "verifikator": {
                    "type": "object",
                    "$ref": "#/definitions/models.Verifikator"
                }
            }
        },
        "models.Filters": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "operation": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.Inventory": {
            "type": "object",
            "properties": {
                "credit": {
                    "type": "number"
                },
                "debit": {
                    "type": "number"
                },
                "deskripsi": {
                    "type": "string"
                },
                "detail": {
                    "type": "object"
                },
                "id": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                },
                "pendamping": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_pendamping"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_inventory_files"
                    }
                },
                "transaction_at": {
                    "type": "string"
                }
            }
        },
        "models.Jn": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "object"
                }
            }
        },
        "models.Kehadiran": {
            "type": "object",
            "properties": {
                "id_pelatihan": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "kehadiran": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_kehadiran"
                    }
                }
            }
        },
        "models.Kube": {
            "type": "object",
            "properties": {
                "bantuan": {
                    "type": "number"
                },
                "created_by": {
                    "type": "string"
                },
                "fb": {
                    "type": "string"
                },
                "id_jenis_usaha": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "ig": {
                    "type": "string"
                },
                "inventaris_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_inventory"
                    }
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Kubes_items"
                    }
                },
                "jenis_usaha": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_jenis_usaha"
                },
                "lapkeu_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_lapkeu"
                    }
                },
                "monev_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_monev_final"
                    }
                },
                "nama_kube": {
                    "type": "string"
                },
                "nama_usaha": {
                    "type": "string"
                },
                "pelatihan_history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_pelatihan"
                    }
                },
                "pendamping": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_pendamping"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_uepkube_files"
                    }
                },
                "region": {
                    "type": "object",
                    "$ref": "#/definitions/models.View_address"
                },
                "status": {
                    "type": "integer"
                },
                "updated_by": {
                    "type": "string"
                },
                "wa": {
                    "type": "string"
                }
            }
        },
        "models.Kubes_items": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fb": {
                    "type": "string"
                },
                "flag": {
                    "type": "string"
                },
                "id_kabupaten": {
                    "type": "integer"
                },
                "id_kecamatan": {
                    "type": "integer"
                },
                "id_kelurahan": {
                    "type": "string"
                },
                "id_user": {
                    "type": "integer"
                },
                "ig": {
                    "type": "string"
                },
                "is_eligible": {
                    "type": "boolean"
                },
                "jenis_kelamin": {
                    "type": "string",
                    "enum": [
                        "L",
                        " P"
                    ]
                },
                "kabupaten": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kabupaten"
                },
                "kecamatan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kecamatan"
                },
                "kelurahan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kelurahan"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "nama": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "no_hp": {
                    "type": "string"
                },
                "no_kk": {
                    "type": "string"
                },
                "posisi": {
                    "type": "string"
                },
                "region": {
                    "type": "object",
                    "$ref": "#/definitions/models.View_address"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "tgl_lahir": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wa": {
                    "type": "string"
                }
            }
        },
        "models.Lapkeu": {
            "type": "object",
            "properties": {
                "bulan": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "detail": {
                    "type": "object"
                },
                "id": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                },
                "modal": {
                    "type": "number"
                },
                "omset": {
                    "type": "number"
                },
                "pendamping": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_pendamping"
                },
                "pendapatan": {
                    "type": "number"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_lapkeu_files"
                    }
                },
                "tahun": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "models.Monev": {
            "type": "object",
            "properties": {
                "id_indikator": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                }
            }
        },
        "models.Pelatihan": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "deskripsi": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_pelatihan_files"
                    }
                },
                "id_pelatihan": {
                    "type": "integer"
                },
                "instruktur": {
                    "type": "string"
                },
                "judul_pelatihan": {
                    "type": "string"
                },
                "kehadiran": {
                    "description": "Kehadiran \t\t\t[]PelatihanKehadiran\t` + "`" + `json:\"kehadiran\"` + "`" + `",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_kehadiran"
                    }
                },
                "lokasi_pelatihan": {
                    "type": "string"
                },
                "peruntukan": {
                    "type": "string",
                    "enum": [
                        "UEP",
                        " KUBE",
                        " UEP-KUBE"
                    ]
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_pelatihan_files"
                    }
                },
                "quota": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "models.Pendamping": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fb": {
                    "type": "string"
                },
                "flag": {
                    "type": "string"
                },
                "id_kabupaten": {
                    "type": "integer"
                },
                "id_kecamatan": {
                    "type": "integer"
                },
                "id_kelurahan": {
                    "type": "string"
                },
                "id_roles": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "ig": {
                    "type": "string"
                },
                "is_eligible": {
                    "type": "boolean"
                },
                "jenis_kelamin": {
                    "type": "string",
                    "enum": [
                        "L",
                        " P"
                    ]
                },
                "jenis_pendamping": {
                    "type": "string"
                },
                "kabupaten": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kabupaten"
                },
                "kecamatan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kecamatan"
                },
                "kelurahan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kelurahan"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "nama": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "no_hp": {
                    "type": "string"
                },
                "no_kk": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "periode": {
                    "type": "string"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_user_files"
                    }
                },
                "region": {
                    "type": "object",
                    "$ref": "#/definitions/models.View_address"
                },
                "roles_name": {
                    "type": "string"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "tgl_lahir": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "wa": {
                    "type": "string"
                }
            }
        },
        "models.PosPagin": {
            "type": "object",
            "properties": {
                "filters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Filters"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 10
                },
                "sortField": {
                    "type": "string",
                    "example": "created_at"
                },
                "sortOrder": {
                    "type": "string",
                    "example": "desc"
                }
            }
        },
        "models.Produk": {
            "type": "object",
            "properties": {
                "deskripsi": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_jp": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                },
                "jenis_produk": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_jenis_produk"
                },
                "nama_produk": {
                    "type": "string"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_produk_files"
                    }
                }
            }
        },
        "models.Tbl_activity_files": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_activity": {
                    "type": "integer"
                },
                "is_display": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "PDF",
                        " IMAGE"
                    ]
                }
            }
        },
        "models.Tbl_inventory": {
            "type": "object",
            "properties": {
                "credit": {
                    "type": "number"
                },
                "debit": {
                    "type": "number"
                },
                "deskripsi": {
                    "type": "string"
                },
                "detail": {
                    "type": "object"
                },
                "id": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                },
                "pendamping": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_pendamping"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_inventory_files"
                    }
                },
                "transaction_at": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_inventory_files": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_inventory": {
                    "type": "integer"
                },
                "is_display": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "PDF",
                        " IMAGE"
                    ]
                }
            }
        },
        "models.Tbl_jenis_produk": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_jenis_usaha": {
            "type": "object",
            "properties": {
                "id_usaha": {
                    "type": "integer"
                },
                "jenis_usaha": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_kabupaten": {
            "type": "object",
            "properties": {
                "id_kabupaten": {
                    "type": "string"
                },
                "kabupaten": {
                    "type": "string"
                },
                "kecamatan": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_kecamatan"
                    }
                }
            }
        },
        "models.Tbl_kecamatan": {
            "type": "object",
            "properties": {
                "id_kabupaten": {
                    "type": "string"
                },
                "id_kecamatan": {
                    "type": "string"
                },
                "kecamatan": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_kehadiran": {
            "type": "object",
            "properties": {
                "flag": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_pelatihan": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "nama": {
                    "type": "string"
                },
                "pelatihan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_pelatihan"
                }
            }
        },
        "models.Tbl_kelurahan": {
            "type": "object",
            "properties": {
                "id_kelurahan": {
                    "type": "string"
                },
                "kelurahan": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_lapkeu": {
            "type": "object",
            "properties": {
                "bulan": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "detail": {
                    "type": "object"
                },
                "id": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                },
                "modal": {
                    "type": "number"
                },
                "omset": {
                    "type": "number"
                },
                "pendamping": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_pendamping"
                },
                "pendapatan": {
                    "type": "number"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_lapkeu_files"
                    }
                },
                "tahun": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_lapkeu_files": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_lapkeu": {
                    "type": "integer"
                },
                "is_display": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "PDF",
                        " IMAGE"
                    ]
                }
            }
        },
        "models.Tbl_monev_category": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "rank": {
                    "type": "string",
                    "enum": [
                        "A",
                        " B",
                        " C"
                    ]
                }
            }
        },
        "models.Tbl_monev_final": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_monev_category"
                },
                "created_at": {
                    "type": "string"
                },
                "data_monev": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Data_monev"
                    }
                },
                "detail": {
                    "type": "object"
                },
                "id": {
                    "type": "integer"
                },
                "id_category": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                },
                "is_monev": {
                    "type": "string",
                    "enum": [
                        "SUDAH",
                        " BELUM"
                    ]
                },
                "pendamping": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_pendamping"
                },
                "sum_total": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_pelatihan": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "deskripsi": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_pelatihan_files"
                    }
                },
                "id_pelatihan": {
                    "type": "integer"
                },
                "instruktur": {
                    "type": "string"
                },
                "judul_pelatihan": {
                    "type": "string"
                },
                "kehadiran": {
                    "description": "Kehadiran \t\t\t[]PelatihanKehadiran\t` + "`" + `json:\"kehadiran\"` + "`" + `",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_kehadiran"
                    }
                },
                "lokasi_pelatihan": {
                    "type": "string"
                },
                "peruntukan": {
                    "type": "string",
                    "enum": [
                        "UEP",
                        " KUBE",
                        " UEP-KUBE"
                    ]
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_pelatihan_files"
                    }
                },
                "quota": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_pelatihan_files": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_pelatihan": {
                    "type": "integer"
                },
                "is_display": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "PDF",
                        " IMAGE"
                    ]
                }
            }
        },
        "models.Tbl_pendamping": {
            "type": "object",
            "properties": {
                "id_pendamping": {
                    "type": "integer"
                },
                "jenis_pendamping": {
                    "type": "string",
                    "enum": [
                        "UEP",
                        " KUBE",
                        " UEPKUBE"
                    ]
                },
                "nama": {
                    "type": "string"
                },
                "periode": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_produk_files": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_produk": {
                    "type": "integer"
                },
                "is_display": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "PDF",
                        " IMAGE"
                    ]
                }
            }
        },
        "models.Tbl_uepkube_files": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                },
                "is_display": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "PDF",
                        " IMAGE"
                    ]
                }
            }
        },
        "models.Tbl_user_files": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "files": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "is_display": {
                    "type": "integer"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "PDF",
                        " IMAGE"
                    ]
                }
            }
        },
        "models.Uep": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "bantuan": {
                    "description": "Id_periods\t\tint \t` + "`" + `json:\"id_periods\"` + "`" + `",
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fb": {
                    "type": "string"
                },
                "flag": {
                    "type": "string"
                },
                "id_jenis_usaha": {
                    "type": "integer"
                },
                "id_kabupaten": {
                    "type": "integer"
                },
                "id_kecamatan": {
                    "type": "integer"
                },
                "id_kelurahan": {
                    "type": "string"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "ig": {
                    "type": "string"
                },
                "is_eligible": {
                    "type": "boolean"
                },
                "jenis_kelamin": {
                    "type": "string",
                    "enum": [
                        "L",
                        " P"
                    ]
                },
                "kabupaten": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kabupaten"
                },
                "kecamatan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kecamatan"
                },
                "kelurahan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kelurahan"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "nama": {
                    "type": "string"
                },
                "nama_usaha": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "no_hp": {
                    "type": "string"
                },
                "no_kk": {
                    "type": "string"
                },
                "region": {
                    "type": "object",
                    "$ref": "#/definitions/models.View_address"
                },
                "status": {
                    "type": "integer"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "tgl_lahir": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wa": {
                    "type": "string"
                }
            }
        },
        "models.Verifikator": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fb": {
                    "type": "string"
                },
                "flag": {
                    "type": "string"
                },
                "id_kabupaten": {
                    "type": "integer"
                },
                "id_kecamatan": {
                    "type": "integer"
                },
                "id_kelurahan": {
                    "type": "string"
                },
                "id_roles": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "ig": {
                    "type": "string"
                },
                "is_eligible": {
                    "type": "boolean"
                },
                "jenis_kelamin": {
                    "type": "string",
                    "enum": [
                        "L",
                        " P"
                    ]
                },
                "kabupaten": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kabupaten"
                },
                "kecamatan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kecamatan"
                },
                "kelurahan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Tbl_kelurahan"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "nama": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "no_hp": {
                    "type": "string"
                },
                "no_kk": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_user_files"
                    }
                },
                "region": {
                    "type": "object",
                    "$ref": "#/definitions/models.View_address"
                },
                "roles_name": {
                    "type": "string"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "tgl_lahir": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "wa": {
                    "type": "string"
                }
            }
        },
        "models.View_address": {
            "type": "object",
            "properties": {
                "id_kabupaten": {
                    "type": "integer"
                },
                "id_kecamatan": {
                    "type": "integer"
                },
                "id_kelurahan": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "157.245.55.185:9093",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "UepKube API",
	Description: "The Documentation for UepKube REST API, Enjoyed..",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
