// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-12-11 13:34:04.612864093 +0700 WIB m=+0.063654291

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "-\u003e @h4sb1",
            "email": "justhasby@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add/{key}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "Add -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu ",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Add ItemsUepKubePendamping",
                        "name": "sample",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Dummy"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth-Controller"
                ],
                "summary": "SignIn",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/address": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetAllAddress",
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "region",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/bantuan_periods": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllBantuanPeriods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/faq": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetAllFaq",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/jenis_usaha": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllJenisUsaha",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/member_pelatihan": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllMemberPelatihan",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "int",
                        "name": "id_pendamping",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/monev_items": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllMonevItems",
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "flag",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/pendamping": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllPendamping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/persebaran": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GeAllUepKubeDetail",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/uepkube": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "Get Uep (byNik) or Get Kube (byName)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "string",
                        "name": "val",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/uepkube/pelatihan": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetPaginatePelatihanUepKube",
                "parameters": [
                    {
                        "description": "Show Pelatihan UepKube",
                        "name": "produk",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.PosPagin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/lookup/uepkube/produk": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Lookup-Controller"
                ],
                "summary": "GetPaginateProduk",
                "parameters": [
                    {
                        "description": "Show Produk UepKube",
                        "name": "produk",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.PosPagin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/upload/images/{key}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "multipart/form-data"
                ],
                "tags": [
                    "UploadImages-Controller"
                ],
                "summary": "UploadsImages -\u003e uep | kube | pendamping | verifikator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key (string) -\u003e uep | kube | pendamping | verifikator",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "id (int)",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Uploads Files",
                        "name": "photo",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "int (int) -\u003e 0 | 1",
                        "name": "is_display",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/{key}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "GetDetails -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "int",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "for (int) -\u003e uep : 0 | kube : 1",
                        "name": "for",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "Update -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu ",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update ItemsUepKubePendamping",
                        "name": "sample",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.Dummy"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "Paginate -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Paginate ItemsUepKubePendamping| verifikator",
                        "name": "sample",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/models.PosPagin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        },
        "/{key}/{id}": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Universal-Controller"
                ],
                "summary": "Delete -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu ",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Id -\u003e uep | kube | pendamping | verifikator | produk | pelatihan | activity | inventaris | laporanKeu ",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Jn"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Dummy": {
            "type": "object",
            "properties": {
                "kube": {
                    "type": "object",
                    "$ref": "#/definitions/models.Kube"
                },
                "pelatihan": {
                    "type": "object",
                    "$ref": "#/definitions/models.Pelatihan"
                },
                "pendamping": {
                    "type": "object",
                    "$ref": "#/definitions/models.Pendamping"
                },
                "produk": {
                    "type": "object",
                    "$ref": "#/definitions/models.Produk"
                },
                "uep": {
                    "type": "object",
                    "$ref": "#/definitions/models.Uep"
                },
                "verifikator": {
                    "type": "object",
                    "$ref": "#/definitions/models.Verifikator"
                }
            }
        },
        "models.Filters": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "operation": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.Jn": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "object"
                }
            }
        },
        "models.Kube": {
            "type": "object",
            "properties": {
                "anggota1": {
                    "type": "integer"
                },
                "anggota2": {
                    "type": "integer"
                },
                "anggota3": {
                    "type": "integer"
                },
                "anggota4": {
                    "type": "integer"
                },
                "anggota5": {
                    "type": "integer"
                },
                "anggota6": {
                    "type": "integer"
                },
                "anggota7": {
                    "type": "integer"
                },
                "bendahara": {
                    "type": "integer"
                },
                "created_by": {
                    "type": "string"
                },
                "fb": {
                    "type": "string"
                },
                "id_jenis_usaha": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_periods": {
                    "type": "integer"
                },
                "ig": {
                    "type": "string"
                },
                "ketua": {
                    "type": "integer"
                },
                "nama_kube": {
                    "type": "string"
                },
                "nama_usaha": {
                    "type": "string"
                },
                "sekertaris": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "updated_by": {
                    "type": "string"
                },
                "wa": {
                    "type": "string"
                }
            }
        },
        "models.Pelatihan": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "deskripsi": {
                    "type": "string"
                },
                "id_pelatihan": {
                    "type": "integer"
                },
                "judul_pelatihan": {
                    "type": "string"
                },
                "lokasi_pelatihan": {
                    "type": "string"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_pelatihan_photo"
                    }
                },
                "tanggal_pelatihan": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "models.Pendamping": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fb": {
                    "type": "string"
                },
                "id_kabupaten": {
                    "type": "integer"
                },
                "id_kecamatan": {
                    "type": "integer"
                },
                "id_kelurahan": {
                    "type": "string"
                },
                "id_roles": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "ig": {
                    "type": "string"
                },
                "jenis_kelamin": {
                    "type": "string",
                    "enum": [
                        "L",
                        " P"
                    ]
                },
                "jenis_pendamping": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "nama": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "no_hp": {
                    "type": "string"
                },
                "no_kk": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "periode": {
                    "type": "string"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_user_photo"
                    }
                },
                "roles_name": {
                    "type": "string"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "tgl_lahir": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "wa": {
                    "type": "string"
                }
            }
        },
        "models.PosPagin": {
            "type": "object",
            "properties": {
                "filters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Filters"
                    }
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "size": {
                    "type": "integer",
                    "example": 10
                },
                "sortField": {
                    "type": "string",
                    "example": "created_at"
                },
                "sortOrder": {
                    "type": "string",
                    "example": "desc"
                }
            }
        },
        "models.Produk": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "id_kube": {
                    "type": "integer"
                },
                "id_produk": {
                    "type": "integer"
                },
                "id_uep": {
                    "type": "integer"
                },
                "id_usaha": {
                    "type": "integer"
                }
            }
        },
        "models.Tbl_pelatihan_photo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "id_pelatihan": {
                    "type": "integer"
                },
                "is_display": {
                    "type": "integer"
                },
                "photo": {
                    "type": "string"
                }
            }
        },
        "models.Tbl_user_photo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "is_display": {
                    "type": "integer"
                },
                "photo": {
                    "type": "string"
                }
            }
        },
        "models.Uep": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fb": {
                    "type": "string"
                },
                "id_jenis_usaha": {
                    "type": "integer"
                },
                "id_kabupaten": {
                    "type": "integer"
                },
                "id_kecamatan": {
                    "type": "integer"
                },
                "id_kelurahan": {
                    "type": "string"
                },
                "id_pendamping": {
                    "type": "integer"
                },
                "id_periods": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "ig": {
                    "type": "string"
                },
                "jenis_kelamin": {
                    "type": "string",
                    "enum": [
                        "L",
                        " P"
                    ]
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "nama": {
                    "type": "string"
                },
                "nama_usaha": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "no_hp": {
                    "type": "string"
                },
                "no_kk": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "tgl_lahir": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "wa": {
                    "type": "string"
                }
            }
        },
        "models.Verifikator": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "fb": {
                    "type": "string"
                },
                "id_kabupaten": {
                    "type": "integer"
                },
                "id_kecamatan": {
                    "type": "integer"
                },
                "id_kelurahan": {
                    "type": "string"
                },
                "id_roles": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "ig": {
                    "type": "string"
                },
                "jenis_kelamin": {
                    "type": "string",
                    "enum": [
                        "L",
                        " P"
                    ]
                },
                "lat": {
                    "type": "number"
                },
                "lng": {
                    "type": "number"
                },
                "nama": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "no_hp": {
                    "type": "string"
                },
                "no_kk": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Tbl_user_photo"
                    }
                },
                "roles_name": {
                    "type": "string"
                },
                "tempat_lahir": {
                    "type": "string"
                },
                "tgl_lahir": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "wa": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:9093",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "UepKube API",
	Description: "The Documentation for UepKube REST API, Enjoyed..",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
